library(devtools)
devtools::install_github("strengejacke/sjPlot")
install.packages("rlang")
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(ggplot2)
library(dplyr)
library(parameters)
sessionInfo()

set_theme(base = theme_classic(base_size = 24), axis.textsize = 1.0, 
          axis.title.size = 1.0, legend.size = 0.7, geom.label.size = 6)

data <- read.csv(file.choose())
head(data)

mydf <- find_var(data, pattern = "Q8", out = "df")
plot_likert(mydf, 
            axis.titles = c("Perceived usefulness", "Percentages"),
            axis.labels = c("Helps me decide what available solutions are suitable for solving problem in hand", 
                            "Would enhance the experimentation process in data science workflow",
                            "Makes designing experiments easier", 
                            "The proposed tool is not useful"))
plot_likert(items = mydf,
            groups = NULL,
            groups.titles = "auto",
            #title = "Perceived usefulness",
            legend.title = NULL,
            legend.labels = c("Strongly Disagree", "Disagree", "Agree", "Strongly Agree", "Neutral"),
            axis.titles = c("Perceived usefulness", "Percentages"),
            axis.labels = c("Helps me decide what available solutions are suitable for solving problem in hand", 
                            "Would enhance the experimentation process in data science workflow",
                            "Makes designing experiments easier", 
                            "The proposed tool is not useful"),
            catcount = 4,
            cat.neutral = 5,
            sort.frq = NULL,
            weight.by = NULL,
            title.wtd.suffix = NULL,
            wrap.title = 30,
            wrap.labels = 20,
            wrap.legend.title = 20,
            wrap.legend.labels = 18,
            geom.size = 0.6,
            geom.colors = "BrBG",
            cat.neutral.color = "grey70",
            intercept.line.color = "grey50",
            reverse.colors = FALSE,
            values = "show",
            show.n = TRUE,
            show.legend = TRUE,
            show.prc.sign = FALSE,
            grid.range = 1,
            grid.breaks = 0.2,
            expand.grid = TRUE,
            digits = 1,
            reverse.scale = FALSE,
            coord.flip = TRUE,
            sort.groups = TRUE,
            legend.pos = "top",
            rel_heights = 1,
            group.legend.options = list(nrow = NULL, byrow = TRUE),
            cowplot.options = list(label_x = 0.01, hjust = 0, align = "v")
)
warnings()

mydf <- find_var(data, pattern = "Q9", out = "df")
# plot_likert(mydf)
plot_likert(items = mydf,
            groups = NULL,
            groups.titles = "auto",
            #title = "Perceived complexity",
            legend.title = NULL,
            legend.labels = c("Strongly Disagree", "Disagree", "Agree", "Strongly Agree", "Neutral"),
            axis.titles = c("Perceived complexity", "Percentages"),
            axis.labels = c("Using the proposed tool is easy and clear", 
                            "I already have the required knowledge to use the proposed tool",
                            "Adapting the proposed tool requires a lot of mental effort", 
                            "I can easily understand the proposed tool"),
            catcount = 4,
            cat.neutral = 5,
            sort.frq = NULL,
            weight.by = NULL,
            title.wtd.suffix = NULL,
            wrap.title = 30,
            wrap.labels = 20,
            wrap.legend.title = 20,
            wrap.legend.labels = 18,
            geom.size = 0.6,
            geom.colors = "BrBG",
            cat.neutral.color = "grey70",
            intercept.line.color = "grey50",
            reverse.colors = FALSE,
            values = "show",
            show.n = TRUE,
            show.legend = TRUE,
            show.prc.sign = FALSE,
            grid.range = 1,
            grid.breaks = 0.2,
            expand.grid = TRUE,
            digits = 1,
            reverse.scale = FALSE,
            coord.flip = TRUE,
            sort.groups = TRUE,
            legend.pos = "top",
            rel_heights = 1,
            group.legend.options = list(nrow = NULL, byrow = TRUE),
            cowplot.options = list(label_x = 0.01, hjust = 0, align = "v")
)

mydf <- find_var(data, pattern = "Q10", out = "df")
# plot_likert(mydf)
plot_likert(items = mydf,
            groups = NULL,
            groups.titles = "auto",
            #title = "Perceived compatibility",
            legend.title = NULL,
            legend.labels = c("Strongly Disagree", "Disagree", "Agree", "Strongly Agree", "Neutral"),
            axis.titles = c("Perceived compatibility", "Percentages"),
            axis.labels = c("Following the proposed tool is compatible with the way I design experiments",
                            "Following the proposed tool would help the way I design experiments"),
            catcount = 4,
            cat.neutral = 5,
            sort.frq = NULL,
            weight.by = NULL,
            title.wtd.suffix = NULL,
            wrap.title = 30,
            wrap.labels = 20,
            wrap.legend.title = 20,
            wrap.legend.labels = 18,
            geom.size = 0.6,
            geom.colors = "BrBG",
            cat.neutral.color = "grey70",
            intercept.line.color = "grey50",
            reverse.colors = FALSE,
            values = "show",
            show.n = TRUE,
            show.legend = TRUE,
            show.prc.sign = FALSE,
            grid.range = 1,
            grid.breaks = 0.2,
            expand.grid = TRUE,
            digits = 1,
            reverse.scale = FALSE,
            coord.flip = TRUE,
            sort.groups = TRUE,
            legend.pos = "top",
            rel_heights = 1,
            group.legend.options = list(nrow = NULL, byrow = TRUE),
            cowplot.options = list(label_x = 0.01, hjust = 0, align = "v")
)

mydf <- find_var(data, pattern = "Q11", out = "df")
# plot_likert(mydf)
plot_likert(items = mydf,
            groups = NULL,
            groups.titles = "auto",
            #title = "Results demostrability",
            legend.title = NULL,
            legend.labels = c("Strongly Disagree", "Disagree", "Agree", "Strongly Agree", "Neutral"),
            axis.titles = c("Results demonstrability", "Percentages"),
            axis.labels = c("The results of following the proposed tool are apparent to me", 
                            "I have difficulty explaining why adapting the proposed tool makes a difference"),
            catcount = 4,
            cat.neutral = 5,
            sort.frq = NULL,
            weight.by = NULL,
            title.wtd.suffix = NULL,
            wrap.title = 30,
            wrap.labels = 20,
            wrap.legend.title = 20,
            wrap.legend.labels = 18,
            geom.size = 0.6,
            geom.colors = "BrBG",
            cat.neutral.color = "grey70",
            intercept.line.color = "grey50",
            reverse.colors = FALSE,
            values = "show",
            show.n = TRUE,
            show.legend = TRUE,
            show.prc.sign = FALSE,
            grid.range = 1,
            grid.breaks = 0.2,
            expand.grid = TRUE,
            digits = 1,
            reverse.scale = FALSE,
            coord.flip = TRUE,
            sort.groups = TRUE,
            legend.pos = "top",
            rel_heights = 1,
            group.legend.options = list(nrow = NULL, byrow = TRUE),
            cowplot.options = list(label_x = 0.01, hjust = 0, align = "v")
)

mydf <- find_var(data, pattern = "Q12", out = "df")
# plot_likert(mydf)
plot_likert(items = mydf,
            groups = NULL,
            groups.titles = "auto",
            #title = "Behavioral intenetions to use",
            legend.title = NULL,
            legend.labels = c("Strongly Disagree", "Disagree", "Agree", "Strongly Agree", "Neutral"),
            axis.titles = c("Behavioral intentions to use", "Percentages"),
            axis.labels = c("I would like to use the proposed tool when designing experiments", 
                            "I do not think I will use the proposed tool when designing experiments"),
            catcount = 4,
            cat.neutral = 5,
            sort.frq = NULL,
            weight.by = NULL,
            title.wtd.suffix = NULL,
            wrap.title = 30,
            wrap.labels = 20,
            wrap.legend.title = 20,
            wrap.legend.labels = 18,
            geom.size = 0.6,
            geom.colors = "BrBG",
            cat.neutral.color = "grey70",
            intercept.line.color = "grey50",
            reverse.colors = FALSE,
            values = "show",
            show.n = TRUE,
            show.legend = TRUE,
            show.prc.sign = FALSE,
            grid.range = 1,
            grid.breaks = 0.2,
            expand.grid = TRUE,
            digits = 1,
            reverse.scale = FALSE,
            coord.flip = TRUE,
            sort.groups = TRUE,
            legend.pos = "top",
            rel_heights = 1,
            group.legend.options = list(nrow = NULL, byrow = TRUE),
            cowplot.options = list(label_x = 0.01, hjust = 0, align = "v")
)
